examples/automotive/ButtonBar.cpp
examples/automotive/DefaultSkin.cpp
examples/automotive/MainWindow.cpp
examples/automotive/MainWindow.h
examples/automotive/OtherSkin.cpp
examples/automotive/Speedometer.cpp
examples/automotive/Speedometer.h
examples/automotive/SpeedometerDisplay.cpp
examples/automotive/SpeedometerDisplay.h
examples/automotive/SpeedometerSkinlet.cpp
examples/automotive/SpeedometerSkinlet.h
examples/automotive/automotive.pro
examples/automotive/main.cpp
examples/sliders/SliderSkinlet.h

Add a speedometer page to the automotive example.
The control could be moved into skinny or some "advanced controls" folder later.
For a screenshot, see https://twitter.com/peha23/status/981206518476476417

Speedometer

---

examples/automotive/DefaultSkin.cpp
examples/automotive/MainWindow.cpp
examples/automotive/OtherSkin.cpp
examples/automotive/SkinFactory.cpp
examples/automotive/Speedometer.cpp
examples/automotive/Speedometer.h
examples/automotive/SpeedometerDisplay.cpp
examples/automotive/SpeedometerSkinlet.cpp

Speedometer: inherit from QskRangeControl and make skinnable

---

examples/iotdashboard/CircularProgressBar.cpp
examples/iotdashboard/CircularProgressBar.h
examples/iotdashboard/CircularProgressBarSkinlet.cpp
examples/iotdashboard/CircularProgressBarSkinlet.h
examples/iotdashboard/PieChartPainted.cpp
examples/iotdashboard/Skin.cpp
examples/iotdashboard/Skin.h
examples/iotdashboard/iotdashboard.pro

... and use a QskPaintedNode internally. This will make it easier to switch to an arc renderer once it is ready.

Iot dashboard: Make circular progress bar a QskControl

---

contributing-to-QSkinny.md

We need this node to point users to in our CLA

Add note about contributing

---

src/controls/QskPageIndicatorSkinlet.cpp

Bugfix: Respect QskControl::Disabled aspect.

---

qskinny.pro
skins/material/QskMaterialSkin.cpp
skins/squiek/QskSquiekSkin.cpp
src/controls/QskCheckBox.cpp
src/controls/QskCheckBox.h
src/controls/QskCheckBoxSkinlet.cpp
src/controls/QskCheckBoxSkinlet.h
src/controls/QskSkin.cpp
src/src.pro
tests/checkboxes/checkboxes.pro
tests/checkboxes/main.cpp
tests/checkboxes/main.h
tests/tests.pro

Add a Checkbox

---

.github/workflows/qmake.yml
README.md

This extends https://github.com/uwerat/qskinny/pull/81 by using Qt 5.15 and building for both Linux and Windows.
@uwerat : When merging, could you please rebase and leave the commits as they are, so that @oracle2025's commit is still recognizable as his own?

github build action for Linux and Windows

---

src/common/QskAspect.cpp
src/controls/QskMenuSkinlet.cpp
src/controls/QskMenuSkinlet.h

see https://github.com/qskinny/qskinny/runs/6004407590?check_suite_focus=true

fix build on Windows

---

.github/workflows/qmake.yml

... and use powershell after all

CI: Use jom to parallelize the build

---

doc/generate-website.md

website: Add README on how to recreate the website

---

.github/workflows/qmake.yml

@uwerat : Could you please not squash the commits into one commit?

CI system: Add builds for Qt LTS (6.2) and the current Qt version (6.3)

---

src/controls/QskMenuSkinlet.cpp

We need some padding for e.g. the Material 3 style.

QskMenu: Respect graphic padding

---

skins/material/QskMaterialSkin.cpp
skins/squiek/QskSquiekSkin.cpp
src/common/QskAspect.h
src/controls/QskPushButtonSkinlet.cpp

Also, respect the padding hint of the graphic

QskPushButton: respect the graphics alignment

---

src/controls/QskSegmentedBar.cpp
src/controls/QskSegmentedBar.h
src/controls/QskSegmentedBarSkinlet.cpp
src/controls/QskSegmentedBarSkinlet.h

Segmented bar: Allow for styling them for Material 3

---

src/controls/QskSubWindowSkinlet.cpp
src/controls/QskSubWindowSkinlet.h

E.g. Material 3 dialogs have a minimum size

QskSubWindow: Respect minimum size

---

skins/material3/QskMaterial3Skin.cpp
src/controls/QskPushButton.cpp
src/controls/QskPushButton.h
src/controls/QskPushButtonSkinlet.cpp
src/controls/QskPushButtonSkinlet.h

Which e.g. the Material 3 style does

push button: Allow for animations when clicking

---

skins/material3/QskMaterial3Skin.cpp

Material 3: Calculate real pixels from device-independent pixels

---

examples/iotdashboard/BoxWithButtons.cpp
examples/iotdashboard/BoxWithButtons.h
examples/iotdashboard/DashboardPage.cpp
examples/iotdashboard/LightDisplay.cpp
examples/iotdashboard/LightDisplay.h
examples/iotdashboard/LightDisplaySkinlet.cpp
examples/iotdashboard/MyDevices.cpp
examples/iotdashboard/RoundButton.h
examples/iotdashboard/RoundedIcon.cpp
examples/iotdashboard/RoundedIcon.h
examples/iotdashboard/Skin.cpp
examples/iotdashboard/Skin.h

@uwerat : One thing I noticed when clicking the buttons in the indoor temperature and humidity sections is that when clicking fast there is no visual feedback of being in the Pressed state.
Is it because the state is left again before the control is redrawn?
And is there a way to ensure the Pressed state is drawn every time the user clicks on it?

IOT dashboard: Fix styling and make more interactive

---

.github/workflows/qmake.yml

CI: Update current version from 6.3 to 6.4

---

examples/iotdashboard/CircularProgressBar.cpp
examples/iotdashboard/CircularProgressBar.h
examples/iotdashboard/Skin.cpp
examples/iotdashboard/StorageBar.cpp
examples/iotdashboard/StorageBar.h
examples/iotdashboard/StorageBarSkinlet.cpp
examples/iotdashboard/StorageBarSkinlet.h
examples/iotdashboard/StorageMeter.cpp
examples/iotdashboard/StorageMeter.h
examples/iotdashboard/StoragePage.cpp
examples/iotdashboard/StoragePage.h
examples/iotdashboard/iotdashboard.pro

Add IOT example storage page

---

skins/material3/QskMaterial3Skin.cpp

Turns out the button was too small, hence the skewed display.

Material 3: fix push button size

---

examples/gallery/gallery.pro
examples/gallery/main.cpp
examples/gallery/spinbox/SpinBoxPage.cpp
examples/gallery/spinbox/SpinBoxPage.h
skins/material3/QskMaterial3Skin.cpp
src/controls/QskSkin.cpp
src/controls/QskSpinBox.cpp
src/controls/QskSpinBox.h
src/controls/QskSpinBoxSkinlet.cpp
src/controls/QskSpinBoxSkinlet.h
src/src.pro

QskSpinBox

---

examples/gallery/button/ButtonPage.cpp
skins/material3/QskMaterial3Skin.cpp
skins/material3/QskMaterial3Skin.h
src/controls/QskPushButton.cpp
src/controls/QskPushButton.h
src/controls/QskPushButtonSkinlet.cpp

Material 3: Add buttons with variation

---

src/nodes/QskScaleRenderer.cpp
src/nodes/QskScaleRenderer.h
src/nodes/QskTickmarksNode.cpp
src/nodes/QskTickmarksNode.h

tickmarks: support alignment

---

skins/material3/QskMaterial3Skin.cpp
src/inputpanel/QskInputContext.cpp
src/inputpanel/QskInputPanelBox.cpp
src/inputpanel/QskVirtualKeyboard.cpp

A bit of styling to bring the keyboard close to the Android one. Changes wrt re-arranging the layouts yet to come...

M3: Style keyboard

---

skins/fluent2/QskFluent2Skin.cpp
skins/fluent2/QskFluent2Skin.h
skins/fluent2/QskFluent2SkinFactory.cpp
skins/fluent2/metadata.json
skins/material3/QskMaterial3Skin.cpp
skins/material3/QskMaterial3Skin.h
skins/material3/QskMaterial3SkinFactory.cpp
skins/material3/metadata.json
skins/squiek/metadata.json
src/controls/QskSkin.h
src/controls/QskSkinManager.cpp

For now this only reads the color scheme from the QStyleHints; let me know if I should also look into other properties...

style hints: Respect lightness of system when ordering skins

---

skins/material3/QskMaterial3Skin.cpp
src/common/QskAspect.h
src/controls/QskPushButton.cpp
src/controls/QskSegmentedBar.cpp
src/controls/QskSegmentedBar.h
src/controls/QskSegmentedBarSkinlet.cpp
src/controls/QskSegmentedBarSkinlet.h

I had to increase the bits for system control states for this

segmented bar: Support hovered / focused states and style for M3

---

examples/gallery/progressbar/ProgressBarPage.cpp
examples/gallery/progressbar/ProgressBarPage.h
examples/iotdashboard/Skin.cpp
examples/iotdashboard/StoragePage.cpp
qmlexport/QskQml.cpp
skins/fluent2/QskFluent2Skin.cpp
skins/material3/QskMaterial3Skin.cpp
skins/material3/QskMaterial3Skin.h
skins/squiek/QskSquiekSkin.cpp
src/CMakeLists.txt
src/controls/QskProgressBar.cpp
src/controls/QskProgressBar.h
src/controls/QskProgressBarSkinlet.cpp
src/controls/QskProgressIndicator.cpp
src/controls/QskProgressIndicator.h
src/controls/QskProgressIndicatorSkinlet.cpp
src/controls/QskProgressIndicatorSkinlet.h
src/controls/QskProgressRing.cpp
src/controls/QskProgressRing.h
src/controls/QskProgressRingSkinlet.cpp
src/controls/QskProgressRingSkinlet.h
src/controls/QskSkin.cpp

Most of the code between linear and radial bars can be shared with a common superclass QskAbstractProgressBar.
Resolves #98

progress bars: Introduce abstract, linear and radial bars

---

examples/layouts/CMakeLists.txt
examples/layouts/SwipeViewPage.cpp
examples/layouts/SwipeViewPage.h
examples/layouts/main.cpp
src/CMakeLists.txt
src/controls/QskSwipeView.cpp
src/controls/QskSwipeView.h

Add QskSwipeView

---

cmake/QskConfigMacros.cmake

This change allows to build qskinny on all cores

Add msvc parallel build flag

---

doc/tutorials/03-writing-your-first-application.asciidoc

Copies the package list for Qt6 from `README.md` to documentation.

Docs/Qt6 Requirements

---

playground/parrots/main.cpp

Fix M_PI by using qmath

---

cmake/QskBuildFunctions.cmake
qmlexport/CMakeLists.txt
src/CMakeLists.txt
src/common/QskMetaFunction.cpp
src/common/QskMetaInvokable.cpp
src/nodes/QskTreeNode.cpp

Build for WebAssembly including building everything statically etc.

---

src/controls/QskPushButton.cpp

Otherwise we won't re-read the possibly new skin hints

push button: Update after setting the emphasis

---

src/controls/QskAbstractButton.h
src/controls/QskBoundedValueInput.h
src/controls/QskComboBox.h
src/controls/QskGraphicLabel.h
src/controls/QskListView.h
src/controls/QskTabBar.h
src/controls/QskTextInput.h
src/controls/QskTextLabel.h

Issue #395 
Here I added the USER true properties where I thought made sense.
Maybe the Combo Box and List Box are controversial, should they use currentText or currentIndex? I've followed Qt widgets here.
Also, in QskGraphicLabel I've set it to source, but sometimes the graphic is set with setGraphic...

USER properties

---

designsystems/fluent2/QskFluent2Skin.cpp

We can do with a gradient on the handle.

F2 slider: Get rid of Halo subcontrol

---

designsystems/fluent2/QskFluent2Skin.cpp
designsystems/material3/QskMaterial3Skin.cpp

push buttons: Style checked state properly
